"""Self-contained local operator interface assets for NEXUS Agent."""

# ruff: noqa: E501 - minified browser assets are intentionally immutable byte literals

INDEX_HTML = b"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>NEXUS Agent</title><link rel="stylesheet" href="/ui/app.css"></head>
<body><main>
<header><p class="eyebrow">RAD Forge / NEXUS OS</p><h1>NEXUS Agent</h1><p>Qualified planning. Human approval. Verifiable boundaries.</p></header>
<section id="login" class="card"><h2>Operator login</h2><form id="login-form"><label>Password<input id="password" type="password" autocomplete="current-password" required minlength="12"></label><button>Unlock local agent</button></form></section>
<section id="workspace" class="card hidden"><div class="status"><span class="dot"></span>Local session active</div><h2>What should we plan?</h2><form id="goal-form"><label>Project ID<input id="project" value="my_project" pattern="[a-z][a-z0-9_-]{2,63}" required></label><label>Goal<textarea id="objective" rows="5" maxlength="8000" required placeholder="Describe the outcome, constraints, and what success means."></textarea></label><button>Generate governed plan</button></form><p class="note">The model proposes only. Nothing is executed or published from this screen.</p></section>
<section id="review" class="card hidden"><div class="status amber">Human review required</div><h2>Candidate specification</h2><pre id="candidate" tabindex="0"></pre><button id="approve">Approve exact specification</button><p id="digest" class="mono"></p></section>
<div id="message" role="status" aria-live="polite"></div>
</main><script src="/ui/app.js" defer></script></body></html>"""

APP_CSS = b""":root{color-scheme:dark;--bg:#07111f;--card:#0e1b2d;--line:#233651;--text:#ecf4ff;--muted:#9db0c9;--accent:#59d7c5}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#173252,var(--bg) 45%);color:var(--text);font:16px/1.55 system-ui,sans-serif;min-height:100vh}main{width:min(820px,92%);margin:auto;padding:64px 0}header{margin-bottom:30px}h1{font-size:clamp(2.6rem,8vw,5rem);margin:0;letter-spacing:-.06em}h2{margin-top:0}.eyebrow{color:var(--accent);font-weight:700;letter-spacing:.14em}.card{background:rgba(14,27,45,.94);border:1px solid var(--line);border-radius:20px;padding:28px;margin:18px 0;box-shadow:0 20px 60px #0005}.hidden{display:none}label{display:block;color:var(--muted);margin:14px 0}input,textarea{display:block;width:100%;margin-top:7px;padding:13px;border:1px solid #36506f;border-radius:10px;background:#07111f;color:var(--text);font:inherit}button{border:0;border-radius:10px;padding:13px 18px;background:var(--accent);color:#06201c;font-weight:800;cursor:pointer}button:focus,input:focus,textarea:focus,pre:focus{outline:3px solid #fff;outline-offset:3px}.status{color:var(--accent);font-weight:700;margin-bottom:16px}.amber{color:#ffc66d}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--accent);margin-right:8px}pre{white-space:pre-wrap;overflow:auto;background:#07111f;padding:18px;border-radius:12px;border:1px solid var(--line);max-height:55vh}.note,#message{color:var(--muted)}.mono{font:12px ui-monospace,monospace;overflow-wrap:anywhere}@media(prefers-reduced-motion:no-preference){.card{animation:rise .35s ease-out}@keyframes rise{from{opacity:0;transform:translateY(8px)}}}"""

APP_JS = b"""'use strict';
const q=(s)=>document.querySelector(s),msg=q('#message');let token='',session='',digest='';
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers,cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.message||'Request failed safely');return body}
q('#login-form').addEventListener('submit',async(e)=>{e.preventDefault();msg.textContent='Authenticating...';try{const body=await api('/v1/auth/login',{method:'POST',body:JSON.stringify({password:q('#password').value})});token=body.access_token;q('#password').value='';q('#login').classList.add('hidden');q('#workspace').classList.remove('hidden');msg.textContent='Authenticated locally.'}catch(error){msg.textContent=error.message}});
q('#goal-form').addEventListener('submit',async(e)=>{e.preventDefault();msg.textContent='Generating and validating the candidate...';try{const body=await api('/v1/agent/sessions',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()+'-create'},body:JSON.stringify({project_id:q('#project').value,objective:q('#objective').value})});session=body.session_id;const candidate=await api(`/v1/agent/sessions/${session}/candidate`);digest=candidate.candidate_digest;q('#candidate').textContent=JSON.stringify(candidate,null,2);q('#digest').textContent=`Digest: ${digest}`;q('#review').classList.remove('hidden');msg.textContent='Review every field before approval.'}catch(error){msg.textContent=error.message}});
q('#approve').addEventListener('click',async()=>{msg.textContent='Recording exact-digest approval...';try{const body=await api(`/v1/agent/sessions/${session}/approve`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()+'-approve'},body:JSON.stringify({candidate_digest:digest})});msg.textContent=`Approved. Session state: ${body.state}. No work has been executed.`;q('#approve').disabled=true}catch(error){msg.textContent=error.message}});"""
